--liquibase formatted sql

--changeset codex:006-equipment-seed
INSERT INTO equipment(id,payload) VALUES ('barbell','{"name": "Штанга", "group": "Свободные веса", "synonyms": ["гриф"], "provides": ["barbell"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('dumbbells','{"name": "Гантели", "group": "Свободные веса", "synonyms": [], "provides": ["dumbbells"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('kettlebell','{"name": "Гиря", "group": "Свободные веса", "synonyms": [], "provides": ["kettlebell"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('ez_bar','{"name": "EZ-гриф", "group": "Свободные веса", "synonyms": ["кривой гриф"], "provides": ["ez_bar"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('plates','{"name": "Диски", "group": "Свободные веса", "synonyms": ["блины"], "provides": ["plates"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('rack','{"name": "Стойка / силовая рама", "group": "Стойки", "synonyms": ["рама"], "provides": ["rack"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('flat_bench','{"name": "Горизонтальная скамья", "group": "Скамьи", "synonyms": ["плоская скамья"], "provides": ["flat_bench"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('incline_bench','{"name": "Наклонная скамья", "group": "Скамьи", "synonyms": [], "provides": ["incline_bench"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('adjustable_bench','{"name": "Регулируемая скамья", "group": "Скамьи", "synonyms": ["настраиваемая скамья"], "provides": ["adjustable_bench", "flat_bench", "incline_bench"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('decline_bench','{"name": "Скамья с отрицательным наклоном", "group": "Скамьи", "synonyms": ["decline"], "provides": ["decline_bench"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('upper_pulley','{"name": "Верхний блок", "group": "Тренажёры", "synonyms": [], "provides": ["upper_pulley"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('lower_pulley','{"name": "Нижний блок", "group": "Тренажёры", "synonyms": [], "provides": ["lower_pulley"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('crossover','{"name": "Кроссовер", "group": "Тренажёры", "synonyms": [], "provides": ["crossover"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('pullup_bar','{"name": "Турник", "group": "Опоры", "synonyms": ["перекладина"], "provides": ["pullup_bar"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('dip_bars','{"name": "Брусья", "group": "Опоры", "synonyms": [], "provides": ["dip_bars"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('low_bar','{"name": "Низкая перекладина", "group": "Опоры", "synonyms": ["австралийские подтягивания"], "provides": ["low_bar"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('rings','{"name": "Кольца", "group": "Опоры", "synonyms": [], "provides": ["rings"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('parallettes','{"name": "Паралетсы", "group": "Опоры", "synonyms": [], "provides": ["parallettes"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('captains_chair','{"name": "Стойка для подъёма коленей", "group": "Опоры", "synonyms": ["капитанское кресло"], "provides": ["captains_chair"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('support','{"name": "Опора", "group": "Опоры", "synonyms": [], "provides": ["support"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('nordic_bench','{"name": "Скамья для нордических сгибаний", "group": "Специализированное", "synonyms": ["нордическая скамья"], "provides": ["nordic_bench", "ankle_anchor"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('ankle_anchor','{"name": "Фиксатор стоп", "group": "Специализированное", "synonyms": ["анкеры"], "provides": ["ankle_anchor"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('hyperextension_bench','{"name": "Гиперэкстензия", "group": "Специализированное", "synonyms": [], "provides": ["hyperextension_bench"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('reverse_hyper','{"name": "Тренажёр reverse hyper", "group": "Специализированное", "synonyms": [], "provides": ["reverse_hyper"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('t_bar_machine','{"name": "T-гриф", "group": "Специализированное", "synonyms": [], "provides": ["t_bar_machine"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('smith_machine','{"name": "Машина Смита", "group": "Тренажёры", "synonyms": [], "provides": ["smith_machine"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('hack_squat','{"name": "Гакк-тренажёр", "group": "Тренажёры", "synonyms": [], "provides": ["hack_squat"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('leg_press','{"name": "Жим ногами", "group": "Тренажёры", "synonyms": [], "provides": ["leg_press"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('leg_extension','{"name": "Разгибатель ног", "group": "Тренажёры", "synonyms": [], "provides": ["leg_extension"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('leg_curl','{"name": "Сгибатель ног", "group": "Тренажёры", "synonyms": [], "provides": ["leg_curl"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('chest_press_machine','{"name": "Тренажёр для жима", "group": "Тренажёры", "synonyms": [], "provides": ["chest_press_machine"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('pec_deck','{"name": "Пек-дек", "group": "Тренажёры", "synonyms": [], "provides": ["pec_deck"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('shoulder_press_machine','{"name": "Тренажёр для жима плечами", "group": "Тренажёры", "synonyms": [], "provides": ["shoulder_press_machine"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('rear_delt_machine','{"name": "Тренажёр для задней дельты", "group": "Тренажёры", "synonyms": [], "provides": ["rear_delt_machine"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('row_machine','{"name": "Тяговый тренажёр", "group": "Тренажёры", "synonyms": [], "provides": ["row_machine"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('gravitron','{"name": "Гравитрон", "group": "Тренажёры", "synonyms": [], "provides": ["gravitron"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('back_extension_machine','{"name": "Тренажёр для разгибаний спины", "group": "Тренажёры", "synonyms": [], "provides": ["back_extension_machine"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('hip_thrust_machine','{"name": "Тренажёр для хип-траста", "group": "Тренажёры", "synonyms": [], "provides": ["hip_thrust_machine"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('hip_abduction_machine','{"name": "Тренажёр для отведения бедра", "group": "Тренажёры", "synonyms": [], "provides": ["hip_abduction_machine"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('hip_adduction_machine','{"name": "Тренажёр для приведения бедра", "group": "Тренажёры", "synonyms": [], "provides": ["hip_adduction_machine"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('preacher_bench','{"name": "Скамья Скотта", "group": "Скамьи", "synonyms": [], "provides": ["preacher_bench"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('trap_bar','{"name": "Трэп-гриф", "group": "Свободные веса", "synonyms": [], "provides": ["trap_bar"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('rowing_machine','{"name": "Гребной тренажёр", "group": "Кардио", "synonyms": [], "provides": ["rowing_machine"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('treadmill','{"name": "Беговая дорожка", "group": "Кардио", "synonyms": [], "provides": ["treadmill"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('exercise_bike','{"name": "Велотренажёр", "group": "Кардио", "synonyms": [], "provides": ["exercise_bike"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('elliptical','{"name": "Эллипс", "group": "Кардио", "synonyms": ["орбитрек"], "provides": ["elliptical"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('stair_climber','{"name": "Лестничный тренажёр", "group": "Кардио", "synonyms": [], "provides": ["stair_climber"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('stepper','{"name": "Степпер", "group": "Кардио", "synonyms": [], "provides": ["stepper"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('air_bike','{"name": "Air bike", "group": "Кардио", "synonyms": [], "provides": ["air_bike"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('ski_erg','{"name": "SkiErg", "group": "Кардио", "synonyms": [], "provides": ["ski_erg"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('jump_rope','{"name": "Скакалка", "group": "Кардио", "synonyms": [], "provides": ["jump_rope"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('ab_wheel','{"name": "Колесо для пресса", "group": "Аксессуары", "synonyms": [], "provides": ["ab_wheel"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('shrug_machine','{"name": "Тренажёр для шрагов", "group": "Тренажёры", "synonyms": ["трапеция"], "provides": ["shrug_machine"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('box','{"name": "Тумба", "group": "Специализированное", "synonyms": [], "provides": ["box"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('seated_calf_machine','{"name": "Тренажёр для икр сидя", "group": "Тренажёры", "synonyms": [], "provides": ["seated_calf_machine"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('standing_calf_machine','{"name": "Тренажёр для икр стоя", "group": "Тренажёры", "synonyms": [], "provides": ["standing_calf_machine"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('platform','{"name": "Платформа", "group": "Специализированное", "synonyms": [], "provides": ["platform"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('blocks','{"name": "Плинты", "group": "Специализированное", "synonyms": [], "provides": ["blocks"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('board','{"name": "Доска для жима", "group": "Специализированное", "synonyms": [], "provides": ["board"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('resistance_band','{"name": "Резиновая лента", "group": "Аксессуары", "synonyms": ["резинка"], "provides": ["resistance_band"]}'::jsonb);
INSERT INTO equipment(id,payload) VALUES ('pool','{"name": "Бассейн", "group": "Кардио", "synonyms": [], "provides": ["pool"]}'::jsonb);
